## Action 1
- PageRank
    - Simple Model
        - Rank Leak
        - Rank Sink
    - Random Browse

### PageRank Simple Model
$$PR(u) = \sum_{v \in B_u}=\frac{PR(v)}{L(v)}$$
解释：一个网页u的PageRank=所有入链集合的页面的加权PageRank之和，从图论角度来讲，$L(v)$表示图的出度数，$PR(v)$是一个反复迭代的值，如下图所示:

![Example 1](./imgs/example1.png)

其中计算方式为矩阵计算:

![PageRank基本原理](./imgs/example1_1.png)

In [152]:
import copy 

In [204]:
def page_rank_simple(G, personalization=None, max_iter=100, tol=1.0e-10):
    """
    G: 表示图
        上图表示的图为：
        G = {
            'A':['B', 'C', 'D'],
            'B':['A', 'D'],
            'C':['A'],
            'D':['B','C']
        }
    personalization: 表示初始化PR{A:PR of A}
    max_iter: 最大迭代次数，power iteration
    tol: l1 norm限制上限
    """
    # calc weight
    W = {}     # 权重
    node = []  # 节点
    for n2, l in G.items():
        node.append(n2)
        for n1 in l:
            if n1 not in W.keys():
                W[n1] = {}
            W[n1][n2] = 1./len(l)
    print('W', W)
    # initialization PR
    if personalization is None:
        x = {n : 1./len(G) for n in node}
    else:
        x = personalization
    print('X:', x)
    # power iteration
    for _ in range(max_iter):
        xlast = x
        x = dict.fromkeys(xlast.keys(), 0)
        for n in x:
            if n not in W.keys():
                x[n] = 0
                continue
            for nbr in W[n]:
                x[n] += W[n][nbr] * xlast[nbr] 
        err = sum([abs(x[n] - xlast[n]) for n in x])
        print(x)
        # l1 norm
        if err < len(node) * tol:
            return x
    raise ValueError('pagerank: power iteration failed to converge in %d iterations.' % max_iter)

In [210]:
G1 = {
    'A':['B', 'C', 'D'],
    'B':['A', 'D'],
    'C':['A'],
    'D':['B','C']
}
page_rank_simple(G1)

W {'B': {'A': 0.3333333333333333, 'D': 0.5}, 'C': {'A': 0.3333333333333333, 'D': 0.5}, 'D': {'A': 0.3333333333333333, 'B': 0.5}, 'A': {'B': 0.5, 'C': 1.0}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0.375, 'B': 0.20833333333333331, 'C': 0.20833333333333331, 'D': 0.20833333333333331}
{'A': 0.3125, 'B': 0.22916666666666666, 'C': 0.22916666666666666, 'D': 0.22916666666666666}
{'A': 0.34375, 'B': 0.21875, 'C': 0.21875, 'D': 0.21875}
{'A': 0.328125, 'B': 0.22395833333333331, 'C': 0.22395833333333331, 'D': 0.22395833333333331}
{'A': 0.3359375, 'B': 0.22135416666666666, 'C': 0.22135416666666666, 'D': 0.22135416666666666}
{'A': 0.33203125, 'B': 0.22265625, 'C': 0.22265625, 'D': 0.22265625}
{'A': 0.333984375, 'B': 0.22200520833333331, 'C': 0.22200520833333331, 'D': 0.22200520833333331}
{'A': 0.3330078125, 'B': 0.22233072916666666, 'C': 0.22233072916666666, 'D': 0.22233072916666666}
{'A': 0.33349609375, 'B': 0.22216796875, 'C': 0.22216796875, 'D': 0.22216796875}
{'A': 0.333251953125, 

{'A': 0.33333333337213844,
 'B': 0.22222222220928717,
 'C': 0.22222222220928717,
 'D': 0.22222222220928717}

In [211]:
import numpy as np

In [212]:
w = np.array([0.25, 0.25, 0.25, 0.25])
M = np.array([
    [0, 1/2, 1, 0],
    [1/3, 0, 0, 1/2],
    [1/3, 0, 0, 1/2],
    [1/3, 1/2, 0, 0]
])
w, M
for i in range(100):
    w = np.dot(M, w)
    print(w)

[0.375      0.20833333 0.20833333 0.20833333]
[0.3125     0.22916667 0.22916667 0.22916667]
[0.34375 0.21875 0.21875 0.21875]
[0.328125   0.22395833 0.22395833 0.22395833]
[0.3359375  0.22135417 0.22135417 0.22135417]
[0.33203125 0.22265625 0.22265625 0.22265625]
[0.33398438 0.22200521 0.22200521 0.22200521]
[0.33300781 0.22233073 0.22233073 0.22233073]
[0.33349609 0.22216797 0.22216797 0.22216797]
[0.33325195 0.22224935 0.22224935 0.22224935]
[0.33337402 0.22220866 0.22220866 0.22220866]
[0.33331299 0.222229   0.222229   0.222229  ]
[0.33334351 0.22221883 0.22221883 0.22221883]
[0.33332825 0.22222392 0.22222392 0.22222392]
[0.33333588 0.22222137 0.22222137 0.22222137]
[0.33333206 0.22222265 0.22222265 0.22222265]
[0.33333397 0.22222201 0.22222201 0.22222201]
[0.33333302 0.22222233 0.22222233 0.22222233]
[0.33333349 0.22222217 0.22222217 0.22222217]
[0.33333325 0.22222225 0.22222225 0.22222225]
[0.33333337 0.22222221 0.22222221 0.22222221]
[0.33333331 0.22222223 0.22222223 0.22222223]


### Rank Leak
一个网页没有出链，如图

![Rank Leak](./imgs/example1_2.png)

In [213]:
G2 = {
    'A':[],
    'B':['C'],
    'C':['D'],
    'D':['A', 'B']
}
page_rank_simple(G2)

W {'C': {'B': 1.0}, 'D': {'C': 1.0}, 'A': {'D': 0.5}, 'B': {'D': 0.5}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0.125, 'B': 0.125, 'C': 0.25, 'D': 0.25}
{'A': 0.125, 'B': 0.125, 'C': 0.125, 'D': 0.25}
{'A': 0.125, 'B': 0.125, 'C': 0.125, 'D': 0.125}
{'A': 0.0625, 'B': 0.0625, 'C': 0.125, 'D': 0.125}
{'A': 0.0625, 'B': 0.0625, 'C': 0.0625, 'D': 0.125}
{'A': 0.0625, 'B': 0.0625, 'C': 0.0625, 'D': 0.0625}
{'A': 0.03125, 'B': 0.03125, 'C': 0.0625, 'D': 0.0625}
{'A': 0.03125, 'B': 0.03125, 'C': 0.03125, 'D': 0.0625}
{'A': 0.03125, 'B': 0.03125, 'C': 0.03125, 'D': 0.03125}
{'A': 0.015625, 'B': 0.015625, 'C': 0.03125, 'D': 0.03125}
{'A': 0.015625, 'B': 0.015625, 'C': 0.015625, 'D': 0.03125}
{'A': 0.015625, 'B': 0.015625, 'C': 0.015625, 'D': 0.015625}
{'A': 0.0078125, 'B': 0.0078125, 'C': 0.015625, 'D': 0.015625}
{'A': 0.0078125, 'B': 0.0078125, 'C': 0.0078125, 'D': 0.015625}
{'A': 0.0078125, 'B': 0.0078125, 'C': 0.0078125, 'D': 0.0078125}
{'A': 0.00390625, 'B': 0.00390625, 'C': 0

{'A': 2.3283064365386963e-10,
 'B': 2.3283064365386963e-10,
 'C': 2.3283064365386963e-10,
 'D': 4.656612873077393e-10}

### Rank Sink
一个网页只有出链

![Rank Sink](./imgs/example1_3.png)

In [214]:
G3 = {
    'A':['B', 'D'],
    'B':['C'],
    'C':['D'],
    'D':['B'],
}
page_rank_simple(G3, max_iter=100)

W {'B': {'A': 0.5, 'D': 1.0}, 'D': {'A': 0.5, 'C': 1.0}, 'C': {'B': 1.0}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25}
{'A': 0, 'B': 0.25, 'C': 0.375, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.25, 'D': 0.375}
{'A': 0, 'B': 0.375, 'C': 0.375, 'D': 0.25

ValueError: pagerank: power iteration failed to converge in 100 iterations.

### PageRank Random Browse

$$PR(u) = \frac{1-d}{N} + d \sum_{v \in B_u } \frac{PR(v)}{L(v)}$$

In [217]:
def page_rank_rb(G, d=0.85, personalization=None, max_iter=100, tol=1.0e-10):
    """
    G: 表示图
        上图表示的图为：
        G = {
            'A':['B', 'C', 'D'],
            'B':['A', 'D'],
            'C':['A'],
            'D':['B','C']
        }
    personalization: 表示初始化PR{A:PR of A}
    max_iter: 最大迭代次数，power iteration
    tol: l1 norm限制上限
    """
    # calc weight
    W = {}     # 权重
    node = []  # 节点
    for n2, l in G.items():
        node.append(n2)
        for n1 in l:
            if n1 not in W.keys():
                W[n1] = {}
            W[n1][n2] = 1./len(l)
    print('W', W)
    # initialization PR
    if personalization is None:
        x = {n : 1./len(G) for n in node}
    else:
        x = personalization
    print('X:', x)
    # power iteration
    for _ in range(max_iter):
        xlast = x
        x = dict.fromkeys(xlast.keys(), 0)
        for n in x:
            if n not in W.keys():
                x[n] = 0
                continue
            for nbr in W[n]:
                x[n] += W[n][nbr] * xlast[nbr] 
            x[n] = (1-d)/len(l) + d * x[n] 
        err = sum([abs(x[n] - xlast[n]) for n in x])
        print(x)
        # l1 norm
        if err < len(node) * tol:
            return x
    raise ValueError('pagerank: power iteration failed to converge in %d iterations.' % max_iter)

In [219]:
page_rank_rb(G1, max_iter=1000)

W {'B': {'A': 0.3333333333333333, 'D': 0.5}, 'C': {'A': 0.3333333333333333, 'D': 0.5}, 'D': {'A': 0.3333333333333333, 'B': 0.5}, 'A': {'B': 0.5, 'C': 1.0}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0.39375, 'B': 0.2520833333333333, 'C': 0.2520833333333333, 'D': 0.2520833333333333}
{'A': 0.39640625, 'B': 0.29369791666666667, 'C': 0.29369791666666667, 'D': 0.29369791666666667}
{'A': 0.44946484375, 'B': 0.31213671875000004, 'C': 0.31213671875000004, 'D': 0.31213671875000004}
{'A': 0.47297431640625004, 'B': 0.3350064778645833, 'C': 0.3350064778645833, 'D': 0.3350064778645833}
{'A': 0.5021332592773438, 'B': 0.3513871427408854, 'C': 0.3513871427408854, 'D': 0.3513871427408854}
{'A': 0.5230186069946289, 'B': 0.366610625793457, 'C': 0.366610625793457, 'D': 0.366610625793457}
{'A': 0.5424285478866577, 'B': 0.37899812127736404, 'C': 0.37899812127736404, 'D': 0.37899812127736404}
{'A': 0.5582226046286392, 'B': 0.389762290110766, 'C': 0.389762290110766, 'D': 0.389762290110766}
{'A': 0.

{'A': 0.6491228063234684,
 'B': 0.45029239719810177,
 'C': 0.45029239719810177,
 'D': 0.45029239719810177}

In [220]:
page_rank_rb(G2)

W {'C': {'B': 1.0}, 'D': {'C': 1.0}, 'A': {'D': 0.5}, 'B': {'D': 0.5}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0.18125000000000002, 'B': 0.18125000000000002, 'C': 0.2875, 'D': 0.2875}
{'A': 0.19718750000000002, 'B': 0.19718750000000002, 'C': 0.22906250000000003, 'D': 0.31937499999999996}
{'A': 0.210734375, 'B': 0.210734375, 'C': 0.24260937500000002, 'D': 0.26970312500000004}
{'A': 0.18962382812500003, 'B': 0.18962382812500003, 'C': 0.25412421875, 'D': 0.28121796875000005}
{'A': 0.19451763671875003, 'B': 0.19451763671875003, 'C': 0.23618025390625003, 'D': 0.29100558593750003}
{'A': 0.19867737402343752, 'B': 0.19867737402343752, 'C': 0.24033999121093752, 'D': 0.27575321582031254}
{'A': 0.19219511672363282, 'B': 0.19219511672363282, 'C': 0.2438757679199219, 'D': 0.2792889925292969}
{'A': 0.19369782182495118, 'B': 0.19369782182495118, 'C': 0.2383658492150879, 'D': 0.2822944027319336}
{'A': 0.1949751211610718, 'B': 0.1949751211610718, 'C': 0.23964314855120852, 'D': 0.277610971

{'A': 0.1933345359503864,
 'B': 0.1933345359503864,
 'C': 0.23933435553184515,
 'D': 0.2784342022973405}

In [222]:
page_rank_rb(G3, max_iter=1000)

W {'B': {'A': 0.5, 'D': 1.0}, 'D': {'A': 0.5, 'C': 1.0}, 'C': {'B': 1.0}}
X: {'A': 0.25, 'B': 0.25, 'C': 0.25, 'D': 0.25}
{'A': 0, 'B': 0.46875, 'C': 0.36250000000000004, 'D': 0.46875}
{'A': 0, 'B': 0.5484375, 'C': 0.5484375, 'D': 0.45812500000000006}
{'A': 0, 'B': 0.5394062500000001, 'C': 0.616171875, 'D': 0.616171875}
{'A': 0, 'B': 0.67374609375, 'C': 0.6084953125000001, 'D': 0.67374609375}
{'A': 0, 'B': 0.7226841796875001, 'C': 0.7226841796875001, 'D': 0.6672210156250001}
{'A': 0, 'B': 0.7171378632812502, 'C': 0.764281552734375, 'D': 0.764281552734375}
{'A': 0, 'B': 0.7996393198242188, 'C': 0.7595671837890626, 'D': 0.7996393198242188}
{'A': 0, 'B': 0.8296934218505859, 'C': 0.8296934218505859, 'D': 0.7956321062207032}
{'A': 0, 'B': 0.8262872902875977, 'C': 0.8552394085729981, 'D': 0.8552394085729981}
{'A': 0, 'B': 0.8769534972870484, 'C': 0.852344196744458, 'D': 0.8769534972870484}
{'A': 0, 'B': 0.8954104726939911, 'C': 0.8954104726939911, 'D': 0.8744925672327893}
{'A': 0, 'B': 0.893

{'A': 0,
 'B': 0.9999999994225659,
 'C': 0.9999999994225659,
 'D': 0.999999999307079}

### Simple Model vs Random Browse
- 可以利用提升max_iter，使得Rank Leak、Rank Sink特殊情况得到处理。
- 保持原有排序

## Action 2
- TextRank
    - jieba

In [ ]:
# https://github.com/fxsjy/jieba/blob/master/jieba/analyse/textrank.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals
import sys
from operator import itemgetter
from collections import defaultdict
import jieba.posseg
from .tfidf import KeywordExtractor
from .._compat import *


class UndirectWeightedGraph:
    d = 0.85

    def __init__(self):
        self.graph = defaultdict(list)

    def addEdge(self, start, end, weight):
        # use a tuple (start, end, weight) instead of a Edge object
        self.graph[start].append((start, end, weight))
        self.graph[end].append((end, start, weight))

    def rank(self):
        ws = defaultdict(float)
        outSum = defaultdict(float)

        wsdef = 1.0 / (len(self.graph) or 1.0)
        for n, out in self.graph.items():
            ws[n] = wsdef
            outSum[n] = sum((e[2] for e in out), 0.0)

        # this line for build stable iteration
        sorted_keys = sorted(self.graph.keys())
        for x in xrange(10):  # 10 iters
            for n in sorted_keys:
                s = 0
                for e in self.graph[n]:
                    s += e[2] / outSum[e[1]] * ws[e[1]]
                ws[n] = (1 - self.d) + self.d * s

        (min_rank, max_rank) = (sys.float_info[0], sys.float_info[3])

        for w in itervalues(ws):
            if w < min_rank:
                min_rank = w
            if w > max_rank:
                max_rank = w

        for n, w in ws.items():
            # to unify the weights, don't *100.
            ws[n] = (w - min_rank / 10.0) / (max_rank - min_rank / 10.0)

        return ws


class TextRank(KeywordExtractor):

    def __init__(self):
        self.tokenizer = self.postokenizer = jieba.posseg.dt  # 切词工具
        self.stop_words = self.STOP_WORDS.copy()  # 停用词
        self.pos_filt = frozenset(('ns', 'n', 'vn', 'v'))  # 词性过滤
        self.span = 5

    def pairfilter(self, wp):
        return (wp.flag in self.pos_filt and len(wp.word.strip()) >= 2
                and wp.word.lower() not in self.stop_words)

    def textrank(self, sentence, topK=20, withWeight=False, allowPOS=('ns', 'n', 'vn', 'v'), withFlag=False):
        """
        Extract keywords from sentence using TextRank algorithm.
        Parameter:
            - topK: return how many top keywords. `None` for all possible words.
            - withWeight: if True, return a list of (word, weight);
                          if False, return a list of words.
            - allowPOS: the allowed POS list eg. ['ns', 'n', 'vn', 'v'].
                        if the POS of w is not in this list, it will be filtered.
            - withFlag: if True, return a list of pair(word, weight) like posseg.cut
                        if False, return a list of words
        """
        self.pos_filt = frozenset(allowPOS)  # 不可修改的allowPOS
        g = UndirectWeightedGraph()  # 
        cm = defaultdict(int)
        words = tuple(self.tokenizer.cut(sentence))
        for i, wp in enumerate(words):
            if self.pairfilter(wp):
                for j in xrange(i + 1, i + self.span):
                    if j >= len(words):
                        break
                    if not self.pairfilter(words[j]):
                        continue
                    if allowPOS and withFlag:
                        cm[(wp, words[j])] += 1
                    else:
                        cm[(wp.word, words[j].word)] += 1

        for terms, w in cm.items():
            g.addEdge(terms[0], terms[1], w)
        nodes_rank = g.rank()
        if withWeight:
            tags = sorted(nodes_rank.items(), key=itemgetter(1), reverse=True)
        else:
            tags = sorted(nodes_rank, key=nodes_rank.__getitem__, reverse=True)

        if topK:
            return tags[:topK]
        else:
            return tags

    extract_tags = textrank

In [228]:
from textrank4zh import TextRank4Keyword, TextRank4Sentence

with open('dataset/news.txt') as f:
    text = f.read()

tr4w = TextRank4Keyword()
tr4w.analyze(text=text, lower=True, window=2)
print('关键词：')
for item in tr4w.get_keywords(20, word_min_len=1):
    print(item.word, item.weight)

tr4s = TextRank4Sentence()
tr4s.analyze(text=text, lower=True, source='all_filters')
print('摘要：')
for item in tr4s.get_key_sentences(num=3):
    print(item.index, item.weight, item.sentence)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\thinksee\AppData\Local\Temp\jieba.cache
Loading model cost 1.384 seconds.
Prefix dict has been built successfully.


关键词：
土耳其 0.04069520917096793
美国 0.0369142527418084
说 0.02446922676052611
没有 0.023786570392058257
袭击 0.017700149279091273
特种部队 0.017412575896103233
炮击 0.017115219350455936
遭到 0.016625479650103248
报道 0.01588545076733542
进行 0.015360109277853728
官员 0.01289429340340466
新闻周刊 0.0124159192792039
军队 0.012101622809814312
炮弹 0.011975939251251714
还击 0.011652728049471862
观察哨 0.011553223050069785
边境 0.01152755141124453
城市 0.01117250958722105
科巴 0.01117250958722105
山丘 0.01117250958722105
摘要：
2 0.08591468923918809 五角大楼一名高级官员说，土耳其军队的炮击非常猛烈，美国人员曾考虑进行还击是出于自卫
5 0.0783434449568913 《新闻周刊》此前曾在周三报道说，目前美国军队的交战规则仍然以自卫为中心，五角大楼还没有发布全面撤出叙利亚的命令
6 0.07572455879841139 这名五角大楼官员说，土耳其部队应该了解美国的位置，不过，这名官员没有具体说明在场人员的确切人数，但表示大约在15到100人之间


## Other Action
- EdgeRank
    - X
- PersonalRank

## Reference

[PageRank Simple Model](https://www.geeksforgeeks.org/page-rank-algorithm-implementation/)