In [1]:
import tensorflow as tf

**Embedding向量**

- 按照索（常数）引查表；
- 按照one-hot编码进行乘法取出相应的数值；

In [2]:
embedding = tf.constant(
    [
        [0.21, 0.41, 0.51, 0.11],
        [0.22, 0.42, 0.52, 0.12],
        [0.23, 0.43, 0.53, 0.13],
        [0.24, 0.44, 0.54, 0.14],
    ], dtype=tf.float32
)

In [3]:
feature_batch = tf.constant([2, 3, 1, 0])

In [4]:
get_embedding1 = tf.nn.embedding_lookup(embedding, feature_batch)

In [5]:
get_embedding1

<tf.Tensor 'embedding_lookup/Identity:0' shape=(4, 4) dtype=float32>

In [6]:
feature_batch_one_hot = tf.one_hot(feature_batch, depth=4)

In [7]:
feature_batch_one_hot

<tf.Tensor 'one_hot:0' shape=(4, 4) dtype=float32>

In [8]:
get_embedding2 = tf.matmul(feature_batch_one_hot, embedding)

In [9]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    embedding1, embedding2 = sess.run([get_embedding1, get_embedding2])
    print(embedding1)
    print(embedding2)
    print(sess.run(feature_batch_one_hot))

[[0.23 0.43 0.53 0.13]
 [0.24 0.44 0.54 0.14]
 [0.22 0.42 0.52 0.12]
 [0.21 0.41 0.51 0.11]]
[[0.23 0.43 0.53 0.13]
 [0.24 0.44 0.54 0.14]
 [0.22 0.42 0.52 0.12]
 [0.21 0.41 0.51 0.11]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [10]:
# 随机初始化embedding向量
embedding = tf.get_variable(name='embedding', shape=[4, 4], dtype=tf.float32, initializer=tf.random_normal_initializer)

In [11]:
embedding

<tf.Variable 'embedding:0' shape=(4, 4) dtype=float32_ref>

In [12]:
feature_batch = tf.constant([2, 3, 1, 0])

In [13]:
get_embedding1 = tf.nn.embedding_lookup(embedding, feature_batch)

In [14]:
feature_batch_one_hot = tf.one_hot(feature_batch, depth=4)

In [15]:
get_embedding2 = tf.matmul(feature_batch_one_hot, embedding)

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    embedding, embedding1, embedding2 = sess.run([embedding, get_embedding1, get_embedding2])
    print(embedding)
    print(embedding1)
    print(embedding2)

[[ 0.03057877  0.833631    0.5891976  -0.25846544]
 [ 1.4779516  -1.4665494  -0.93241465  0.6418597 ]
 [ 0.2655276   0.24751423 -0.57023716  0.64956355]
 [-2.6789153  -0.3966026   0.3470999  -1.3673408 ]]
[[ 0.2655276   0.24751423 -0.57023716  0.64956355]
 [-2.6789153  -0.3966026   0.3470999  -1.3673408 ]
 [ 1.4779516  -1.4665494  -0.93241465  0.6418597 ]
 [ 0.03057877  0.833631    0.5891976  -0.25846544]]
[[ 0.2655276   0.24751423 -0.57023716  0.64956355]
 [-2.6789153  -0.3966026   0.3470999  -1.3673408 ]
 [ 1.4779516  -1.4665494  -0.93241465  0.6418597 ]
 [ 0.03057877  0.833631    0.5891976  -0.25846544]]


## 单维索引
- **slice** 按照指定的下标范围抽取连续区域的子集
- **gather** 按照指定的下标集合从axis=0中抽取子集，适合抽取不连续区域的子集。

In [31]:
embedding = tf.constant(
    [
        [0.21,0.41,0.51,0.11],
        [0.22,0.42,0.52,0.12],
        [0.23,0.43,0.53,0.13],
        [0.24,0.44,0.54,0.14]
    ],dtype=tf.float32)

In [32]:
index_a = tf.Variable([2, 3, 1, 0])
index_a

<tf.Variable 'Variable_6:0' shape=(4,) dtype=int32_ref>

In [33]:
gather_a = tf.gather(embedding, index_a)
gather_a

<tf.Tensor 'GatherV2_3:0' shape=(4, 4) dtype=float32>

In [34]:
gather_a_axis1 = tf.gather(embedding, index_a, axis=1)

In [35]:
b = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
index_b = tf.Variable([2, 4, 6, 8])
gather_b = tf.gather(b, index_b)

In [36]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
#     print(sess.run(embedding))
    print(sess.run(gather_a))
    print(sess.run(gather_b))
    print(sess.run(gather_a_axis1))

[[0.23 0.43 0.53 0.13]
 [0.24 0.44 0.54 0.14]
 [0.22 0.42 0.52 0.12]
 [0.21 0.41 0.51 0.11]]
[3 5 7 9]
[[0.51 0.11 0.41 0.21]
 [0.52 0.12 0.42 0.22]
 [0.53 0.13 0.43 0.23]
 [0.54 0.14 0.44 0.24]]


**多维索引**

In [28]:
a = tf.Variable([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
index_a = tf.Variable([2])

In [37]:
b = tf.get_variable(name='b',shape=[3,3,2],initializer=tf.random_normal_initializer)
index_b = tf.Variable([[0,1,1],[2,2,0]])

**gather_nd**
- 将params索引为indices指定形状的切片数组中(indices代表索引后的数组形状)

**Sparse embedding**


In [44]:
a = tf.SparseTensor(indices=[[0, 0],[1, 2],[1,3]], values=[1, 2, 3], dense_shape=[2, 4])
b = tf.sparse_tensor_to_dense(a)

In [45]:
embedding = tf.constant(
    [
        [0.21,0.41,0.51,0.11],
        [0.22,0.42,0.52,0.12],
        [0.23,0.43,0.53,0.13],
        [0.24,0.44,0.54,0.14]
    ],dtype=tf.float32)

In [46]:
embedding_sparse = tf.nn.embedding_lookup_sparse(embedding, sp_ids=a, sp_weights=None)

In [47]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(embedding_sparse))
    print(sess.run(b))

[[0.22       0.42       0.52       0.12      ]
 [0.235      0.435      0.53499997 0.13499999]]
[[1 0 0 0]
 [0 0 2 3]]
